<?php

namespace Kim1ne\ProductionCalendar\Tests\Unit;

use Kim1ne\ProductionCalendar\Api\CalendarApi;
use Kim1ne\ProductionCalendar\Api\CalendarReferenceData;
use Kim1ne\ProductionCalendar\Calendar;
use Kim1ne\ProductionCalendar\Month;
use Kim1ne\ProductionCalendar\ProductionCalendarFactory;
use Kim1ne\ProductionCalendar\Year;
use PHPUnit\Framework\TestCase;
use DateTime;

class FullFunctionalTest extends TestCase
{
    private $mockApi;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $reference = new CalendarReferenceData(holidays: [
            new DateTime('01.01.2026'),
            new DateTime('02.01.2026'),
            new DateTime('03.01.2026'),
            new DateTime('04.01.2026'),
            new DateTime('05.01.2026'),
            new DateTime('06.01.2026'),
            new DateTime('07.01.2026'),
            new DateTime('08.01.2026'),
            new DateTime('09.01.2026'),
            new DateTime('10.01.2026'),
            new DateTime('11.01.2026'),

            new DateTime('23.02.2026'),
        ]);

        $mockApi = $this->createMock(CalendarApi::class);
        $mockApi->method('getData')->willReturn($reference);

        $this->mockApi = $mockApi;
    }

    public function testJanuary(): void
    {
        $calendar = $this->create2026();
        $year = $calendar->getYear();

        $this->assertInstanceOf(Year::class, $year);
        $this->assertEquals(2026, $year->year);

        $month = $year->getMonth(1);

        $this->assertInstanceOf(Month::class, $month);
        $this->assertEquals(15, $month->workingDays);
        $this->assertEquals(15 * 8, $month->hours);
    }

    public function testFebruary(): void
    {
        $year = $this->create2026()->getYear();
        $month = $year->getMonth(2);

        $this->assertInstanceOf(Month::class, $month);
        $this->assertEquals(19, $month->workingDays);
        $this->assertCount(1, $month->holidays);
    }

    public function testPeriod()
    {
        $calendar = $this->create2026();

        $year = $calendar->periodDates(
            [
                new DateTime('01.01.2026'),
                new DateTime('11.01.2026'),
            ],
            [
                new DateTime('12.01.2026'),
                new DateTime('28.02.2026'),
            ]
        );

        $this->assertInstanceOf(Year::class, $year);
        $this->assertEquals(2026, $year->year);

        $periods = $year->getPeriods();

        $this->assertCount(2, $periods);

        $period1 = $periods[0];
        $firstDay = $period1->getFirstDay()->format('d.m');
        $lastDay = $period1->getLastDay()->format('d.m');

        $this->assertEquals('01.01', $firstDay);
        $this->assertEquals('11.01', $lastDay);

        $period2 = $periods[1];

        $this->assertEquals(31 - 11 + 28, $period2->countDays());

    }

    private function create2026(): Calendar
    {
        return ProductionCalendarFactory::create(2026, api: $this->mockApi);
    }
}